services:
  scanner_app:
    build:
      context: https://github.com/DieMenschenOrganisation/tdot_2023_scanner_app.git
    ports:
      - 8080:443

  scanner_backend:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_backend.git
    ports:
      - 8000:8000
    env_file:
       - database.env
#    network_mode: host

  host_app:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_host_app.git
    ports:
      - 8081:80

  reverse_proxy:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_reverse_proxy.git
    ports:
      - 4321:4321
