services:
  scanner_app:
    build:
      context: https://github.com/DieMenschenOrganisation/tdot_2023_scanner_app.git
    ports:
      - 8080:80

  host_app:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_host_app.git
    ports:
      - 8081:80

  slots_blackjack_app:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_slots.git
    ports:
      - 8082:3000

  roulette:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_roulette.git
    ports:
      - 8083:3000

  backend:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_backend.git
    ports:
      - 8000:8000
    env_file:
       - database.env

  reverse_proxy:
    build: https://github.com/DieMenschenOrganisation/tdot_2023_reverse_proxy.git
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:certs
